# Generated by Django 5.2.9 on 2026-04-29 16:57

import app.models.branch
import app.models.mentors
import app.models.month_hero
import app.models.portfolio
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('map_url', models.URLField(max_length=500)),
                ('is_opened', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], db_index=True, default='opened', max_length=20)),
                ('album', models.JSONField(blank=True, default=list, validators=[app.models.branch.validate_album])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'branches',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CoinProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='coin-products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coin product',
                'verbose_name_plural': 'Coin products',
                'db_table': 'coin_products',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('image', models.JSONField(blank=True, default=dict, validators=[app.models.portfolio.validate_portfolio_image])),
                ('desc', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfoliolar',
                'db_table': 'portfolios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998XXXXXXXXX formatida bo‘lishi kerak.', regex='^\\+998\\d{9}$')])),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('guest', 'Guest')], default='student', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=80)),
                ('exp', models.CharField(max_length=50)),
                ('students_count', models.CharField(max_length=50)),
                ('working_period_start', models.DateField()),
                ('avatar', models.JSONField(blank=True, default=dict, validators=[app.models.mentors.validate_avatar])),
                ('socials', models.JSONField(blank=True, default=dict, validators=[app.models.mentors.validate_socials])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentors', to='app.branch')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentorlar',
                'db_table': 'mentors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.course')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.module')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['module__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('date', models.CharField(help_text='Masalan: 15-may, 20-iyun, 01-avgust', max_length=50, verbose_name='Sana')),
                ('type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('announcement', 'Announcement'), ('event', 'Event')], max_length=30, verbose_name='Turi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('color', models.CharField(default='#01E0EE', max_length=7, validators=[django.core.validators.RegexValidator(message='Rang HEX formatda bo‘lishi kerak. Masalan: #01E0EE', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Rang')),
                ('icon', models.CharField(default='zap', help_text='Masalan: zap, calendar, megaphone, trophy', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='news_type_a260ae_idx'), models.Index(fields=['is_active'], name='news_is_acti_69e46a_idx'), models.Index(fields=['created_at'], name='news_created_e7b20c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.JSONField()),
                ('images', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.lesson')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998XXXXXXXXX formatida bo‘lishi kerak.', regex='^\\+998\\d{9}$')])),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('api_score', models.IntegerField(default=0)),
                ('local_test_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(db_index=True, default=0)),
                ('api_coin', models.IntegerField(default=0)),
                ('test_coin', models.IntegerField(default=0)),
                ('lesson_last_coin', models.IntegerField(default=0)),
                ('total_coin', models.IntegerField(db_index=True, default=0)),
                ('all_debtor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('attendance_average_percent', models.FloatField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pdp_access_token', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='app.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='app.course')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(db_index=True, default=app.models.month_hero.current_period, help_text='Oy/yil filter uchun. Masalan: 2026-04-01')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_heroes', to='app.studentprofile')),
            ],
            options={
                'verbose_name': 'Oy qahramoni',
                'verbose_name_plural': 'Oy qahramonlari',
                'db_table': 'month_heroes',
                'ordering': ['-period', '-student_profile__total_score'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='app.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='app.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='TestSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_test_sessions', to='app.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.testsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_lesson_name_per_course'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['group_name'], name='student_pro_group_n_09f9de_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['course'], name='student_pro_course__61392b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['branch'], name='student_pro_branch__04ab76_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['last_synced_at'], name='student_pro_last_sy_62b96d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('api_score__gte', 0)), name='studentprofile_api_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('local_test_score__gte', 0)), name='studentprofile_local_test_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('api_coin__gte', 0)), name='studentprofile_api_coin_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('test_coin__gte', 0)), name='studentprofile_test_coin_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0)), name='studentprofile_total_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('total_coin__gte', 0)), name='studentprofile_total_coin_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_average_percent__gte', 0), ('attendance_average_percent__lte', 100)), name='studentprofile_attendance_between_0_100'),
        ),
        migrations.AddIndex(
            model_name='monthhero',
            index=models.Index(fields=['period'], name='month_heroe_period_6909b6_idx'),
        ),
        migrations.AddIndex(
            model_name='monthhero',
            index=models.Index(fields=['is_active'], name='month_heroe_is_acti_7abade_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthhero',
            constraint=models.UniqueConstraint(fields=('student_profile', 'period'), name='unique_month_hero_per_student_period'),
        ),
        migrations.AddConstraint(
            model_name='testsessionanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uniq_test_session_answer'),
        ),
        migrations.AddConstraint(
            model_name='testsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='uniq_test_session_order'),
        ),
        migrations.AddConstraint(
            model_name='testsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uniq_test_session_question'),
        ),
    ]
