# Generated by Django 5.2.9 on 2026-08-08 14:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_frontend_portal_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='monthhero',
            options={'ordering': ['-period', '-points', '-student_profile__total_score'], 'verbose_name': 'Oy qahramoni', 'verbose_name_plural': 'Oy qahramonlari'},
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='branch',
            name='hours',
            field=models.CharField(blank=True, default='09:00–18:00', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthhero',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text="Shu oyda to'plangan ball. 0 bo'lsa student umumiy bali ishlatiladi."),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='student',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', help_text="Frontend yoki tashqi storage'dagi avatar URL/path.", max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='category',
            field=models.JSONField(help_text='{"uz":"Tadbir","ru":"Событие","en":"Event"}'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='date',
            field=models.CharField(help_text='Masalan: 12.07.2026', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(db_index=True)),
                ('attendance', models.CharField(choices=[('present', 'Qatnashgan'), ('absent', 'Qatnashmagan'), ('late', 'Kechikkan')], default='present', max_length=10)),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('verified', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='app.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_marks', to='app.lesson')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='app.studentprofile')),
            ],
            options={
                'verbose_name': 'O‘quvchi bahosi',
                'verbose_name_plural': 'O‘quvchi baholari',
                'ordering': ['-record_date', 'student_profile__user__first_name'],
                'indexes': [models.Index(fields=['course', 'record_date'], name='app_student_course__b825ce_idx'), models.Index(fields=['student_profile', 'record_date'], name='app_student_student_1b43e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'course', 'record_date'), name='unique_student_mark_per_course_date')],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('aim', models.CharField(blank=True, default='', max_length=255)),
                ('time_table_name', models.CharField(blank=True, default='', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('payment_type', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cashier', models.CharField(blank=True, default='', max_length=255)),
                ('canceled', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='app.studentprofile')),
            ],
            options={
                'verbose_name': 'Student payment history',
                'verbose_name_plural': 'Student payment histories',
                'db_table': 'student_payment_histories',
                'ordering': ['-created_date', '-date', '-created_at'],
                'indexes': [models.Index(fields=['student_profile', 'invoice_number'], name='student_pay_student_4b4bf3_idx'), models.Index(fields=['student_profile', 'created_date'], name='student_pay_student_8e04c2_idx'), models.Index(fields=['student_profile', 'date'], name='student_pay_student_1ec5ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'external_id'), name='unique_student_payment_history_external_id')],
            },
        ),
    ]
