# Generated by Django 5.2.9 on 2026-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_options_alter_monthhero_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_name_per_course',
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_lesson_name_per_module'),
        ),
    ]
