# Generated by Django 5.2.9 on 2026-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_lesson_unique_lesson_name_per_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinorder',
            name='admin_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='balance_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='balance_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='is_admin_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='student_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='telegram_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coinorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20),
        ),
    ]
