# Generated by Django 5.2.9 on 2026-08-20 10:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coinproduct_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinproduct',
            options={'ordering': ['price'], 'verbose_name': 'Coin mahsuloti', 'verbose_name_plural': 'Coin mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Modullar'},
        ),
        migrations.AlterModelOptions(
            name='studentpaymenthistory',
            options={'ordering': ['-created_date', '-date', '-created_at'], 'verbose_name': 'To‘lov tarixi', 'verbose_name_plural': 'To‘lovlar tarixi'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student profili', 'verbose_name_plural': 'Student profillari'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Test sessiyasi', 'verbose_name_plural': 'Test sessiyalari'},
        ),
        migrations.AlterModelOptions(
            name='testsessionanswer',
            options={'verbose_name': 'Test javobi', 'verbose_name_plural': 'Test javoblari'},
        ),
        migrations.AlterModelOptions(
            name='testsessionquestion',
            options={'ordering': ['order'], 'verbose_name': 'Test savoli', 'verbose_name_plural': 'Test savollari'},
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, help_text='PDP invoiceId', max_length=128)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('time_table_name', models.CharField(blank=True, default='', max_length=255)),
                ('time_table_position', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.studentprofile')),
            ],
            options={
                'verbose_name': 'Student invoysi',
                'verbose_name_plural': 'Student invoyslari',
                'db_table': 'student_invoices',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['student_profile', 'invoice_number'], name='student_inv_student_9b20b3_idx'), models.Index(fields=['student_profile', 'invoice_status'], name='student_inv_student_b2c75f_idx'), models.Index(fields=['student_profile', 'time_table_position'], name='student_inv_student_f34a9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'external_id'), name='unique_student_invoice_external_id')],
            },
        ),
    ]
