# Generated by Django 5.2.9 on 2026-08-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def backfill_finished_session_summaries(apps, schema_editor):
    TestSession = apps.get_model("app", "TestSession")
    TestSessionAnswer = apps.get_model("app", "TestSessionAnswer")

    sessions = (
        TestSession.objects.filter(is_finished=True, finalized_at__isnull=True)
        .annotate(answers_total=Count("answers", distinct=True))
        .iterator(chunk_size=200)
    )

    for session in sessions:
        correct = TestSessionAnswer.objects.filter(
            session_id=session.pk,
            is_correct=True,
        ).count()
        answered = session.answers_total or session.answered_count or 0
        total = session.total_questions or 0
        TestSession.objects.filter(pk=session.pk).update(
            correct_count=correct,
            wrong_count=max(0, answered - correct),
            unanswered_count=max(0, total - answered),
            percent=int((correct * 100) / total) if total else 0,
            answered_count=answered,
            finalized_at=session.finished_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_testsession_student_lesson_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savol rewardi',
                'verbose_name_plural': 'Savol rewardlari',
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='unanswered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsessionquestion',
            name='correct_option_snapshot',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='testsessionquestion',
            name='question_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testsessionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_answers', to='app.question'),
        ),
        migrations.AlterField(
            model_name='testsessionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_test_sessions', to='app.question'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['student', 'lesson', 'is_finished', 'started_at'], name='test_session_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['is_finished', 'finished_at'], name='test_session_cleanup_idx'),
        ),
        migrations.AddConstraint(
            model_name='testsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_finished', False)), fields=('student', 'lesson'), name='uniq_active_test_per_student_lesson'),
        ),
        migrations.AddField(
            model_name='studentquestionreward',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_rewards', to='app.question'),
        ),
        migrations.AddField(
            model_name='studentquestionreward',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_rewards', to='app.testsession'),
        ),
        migrations.AddField(
            model_name='studentquestionreward',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studentquestionreward',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='uniq_student_question_reward'),
        ),
        migrations.RunPython(
            backfill_finished_session_summaries,
            migrations.RunPython.noop,
        ),
    ]
