# Generated by Django 5.2.9 on 2026-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_testsession_summary_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="external_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="spent_coin",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("spent_coin__gte", 0)),
                name="studentprofile_spent_coin_gte_0",
            ),
        ),
    ]
